Repository windingtree/sdk, pull requests merged in 2023-06, with the labels that each got.

#17 Client-side contract interactions
  .env.example
  .lintstagedrc
  examples/client/.env.example
  examples/client/package.json
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/client/src/components/Offers.tsx
  examples/client/src/components/RequestForm.tsx
  examples/client/src/components/Requests.tsx
  examples/client/src/components/Tabs.tsx
  examples/client/src/main.tsx
  examples/client/src/providers/WalletProvider/AccountWidget.tsx
  examples/client/src/providers/WalletProvider/ConnectButton.tsx
  examples/client/src/providers/WalletProvider/WalletProviderContext.ts
  examples/client/src/providers/WalletProvider/index.tsx
  examples/client/src/utils.ts
  examples/client/src/vite-env.d.ts
  examples/client/vite.config.ts
  examples/client/yarn.lock
  examples/node/index.ts
  examples/shared/index.ts
  package.json
  src/client/dealsRegistry.ts
  src/client/index.ts
  src/client/requestsRegistry.ts
  src/node/index.ts
  src/shared/deal.ts
  src/shared/messages.ts
  src/shared/options.ts
  src/shared/queue.ts
  src/shared/types.ts
  src/storage/local.ts
  src/utils/contract.ts
  src/utils/contracts.ts
  src/utils/hash.ts
  src/utils/index.ts
  src/utils/time.ts
  src/utils/uid.ts
  src/utils/wallet.ts
  test/shared.messages.spec.ts
  test/utils.hash.spec.ts
  test/utils.time.spec.ts
  test/utils.uid.spec.ts
  yarn.lock
Labels: A-releases, A-tests, C-example, D-hard, T-feature

#18 Client-side contract interactions
  .env.example
  .lintstagedrc
  examples/client/.env.example
  examples/client/package.json
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/client/src/components/Offers.tsx
  examples/client/src/components/RequestForm.tsx
  examples/client/src/components/Requests.tsx
  examples/client/src/components/Tabs.tsx
  examples/client/src/main.tsx
  examples/client/src/providers/WalletProvider/AccountWidget.tsx
  examples/client/src/providers/WalletProvider/ConnectButton.tsx
  examples/client/src/providers/WalletProvider/WalletProviderContext.ts
  examples/client/src/providers/WalletProvider/index.tsx
  examples/client/src/utils.ts
  examples/client/src/vite-env.d.ts
  examples/client/vite.config.ts
  examples/client/yarn.lock
  examples/node/index.ts
  examples/shared/index.ts
  package.json
  src/client/dealsRegistry.ts
  src/client/index.ts
  src/client/requestsRegistry.ts
  src/node/index.ts
  src/shared/deal.ts
  src/shared/messages.ts
  src/shared/options.ts
  src/shared/queue.ts
  src/shared/types.ts
  src/storage/local.ts
  src/utils/contract.ts
  src/utils/contracts.ts
  src/utils/hash.ts
  src/utils/index.ts
  src/utils/time.ts
  src/utils/uid.ts
  src/utils/wallet.ts
  test/shared.messages.spec.ts
  test/utils.hash.spec.ts
  test/utils.time.spec.ts
  test/utils.uid.spec.ts
  yarn.lock
Labels: A-releases, C-example, D-hard, T-feature

#19 Smart contract interaction
  .env.example
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/node/index.ts
  examples/shared/index.ts
  package.json
  src/client/dealsRegistry.ts
  src/client/index.ts
  src/index.ts
  src/node/index.ts
  src/node/requestManager.ts
  src/shared/contracts.ts
  src/shared/deal.ts
  src/shared/options.ts
  src/shared/queue.ts
  src/shared/types.ts
  src/utils/contracts.ts
  src/utils/index.ts
  src/utils/offer.ts
  yarn.lock
Labels: C-example, D-hard, T-debt, T-feature

#20 fix: 🐛 Fixed queue test
  src/shared/queue.ts
  test/shared.queue.spec.ts
Labels: A-tests, D-easy

#21 Node class refactoring and Improving NodeRequestManager
  .prettierrc
  docs/docs/clients.md
  docs/docs/nodes.md
  docs/docs/storage.md
  docs/index.html
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/client/src/components/Offers.tsx
  examples/client/src/components/RequestForm.tsx
  examples/client/src/components/Requests.tsx
  examples/client/src/components/Tabs.tsx
  examples/client/src/providers/WalletProvider/AccountWidget.tsx
  examples/client/src/providers/WalletProvider/WalletProviderContext.ts
  examples/client/src/providers/WalletProvider/index.tsx
  examples/client/src/utils.ts
  examples/node/index.ts
  examples/shared/index.ts
  src/client/dealsRegistry.ts
  src/client/index.ts
  src/client/requestsRegistry.ts
  src/index.ts
  src/node/index.ts
  src/node/requestManager.ts
  src/server/index.ts
  src/shared/cache.ts
  src/shared/contracts.ts
  src/shared/deal.ts
  src/shared/messages.ts
  src/shared/options.ts
  src/shared/pubsub.ts
  src/shared/queue.ts
  src/shared/types.ts
  src/storage/abstract.ts
  src/utils/offer.ts
  src/utils/text.ts
  src/utils/time.ts
  src/utils/wallet.ts
  test/node.requestManager.spec.ts
  test/setup.ts
  test/shared.messages.spec.ts
  test/shared.queue.spec.ts
  test/utils.time.spec.ts
  test/utils.uid.spec.ts
Labels: A-tests, C-example, D-average, T-debt

#23 Client class refactoring and Improving ClientRequestsManager
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/client/src/components/Requests.tsx
  examples/node/index.ts
  package.json
  src/client/dealsManager.ts
  src/client/index.ts
  src/client/requestsManager.ts
  src/client/requestsRegistry.ts
  src/node/requestManager.ts
  test/client.requestManager.spec.ts
  test/node.requestManager.spec.ts
  test/setup.ts
  test/shared.messages.spec.ts
  tsconfig.json
  yarn.lock
Labels: A-tests, C-example, D-average, T-debt, T-feature

#24 Thin Client
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/client/src/components/Requests.tsx
  examples/node/index.ts
  package.json
  src/client/dealsManager.ts
  src/client/index.ts
  src/client/requestsManager.ts
  src/client/requestsRegistry.ts
  src/node/requestManager.ts
  test/client.requestManager.spec.ts
  test/node.requestManager.spec.ts
  test/setup.ts
  test/shared.messages.spec.ts
  tsconfig.json
  yarn.lock
Labels: A-releases

#25 refactor: 💡 `then`-able parts of Queue rewritten to async/await
  src/shared/queue.ts
Labels: D-easy, T-perf

#26 New Queue library
  .github/workflows/test.yml
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/node/index.ts
  src/client/index.ts
  src/node/index.ts
  src/server/index.ts
  src/shared/queue-old.ts
  src/shared/queue.ts
  src/utils/time.ts
  test/node.requestManager.spec.ts
  test/shared.queue-old.spec.ts
  test/shared.queue.spec.ts
  tsconfig.build.json
Labels: D-average, T-feature, T-perf

#28 New libp2p version, new Queue
  .github/workflows/test.yml
  .gitignore
  examples/client/src/App.tsx
  examples/client/src/components/Deals.tsx
  examples/client/src/components/MakeDeal.tsx
  examples/node/index.ts
  package.json
  src/client/index.ts
  src/node/index.ts
  src/server/index.ts
  src/shared/queue-old.ts
  src/shared/queue.ts
  src/utils/time.ts
  test/node.requestManager.spec.ts
  test/shared.queue-old.spec.ts
  test/shared.queue.spec.ts
  tsconfig.build.json
  yarn.lock
Labels: A-releases

#29 Chore/vitest migration
  package.json
  test/client.requestManager.spec.ts
  test/index.spec.ts
  test/node.requestManager.spec.ts
  test/setup.ts
  test/shared.messages.spec.ts
  test/shared.queue-old.spec.ts
  test/shared.queue.spec.ts
  test/utils.logger.spec.ts
  test/utils.text.spec.ts
  test/utils.time.spec.ts
  test/utils.uid.spec.ts
  yarn.lock
Labels: A-tests

#30 Node API authorization
  package.json
  src/node/api/db.ts
  src/node/api/index.ts
  src/node/api/router/admin.ts
  src/node/api/router/user.ts
  src/node/api/server.ts
  test/client.requestManager.spec.ts
  test/node.api.db.spec.ts
  test/node.api.nodeApiServer.spec.ts
  test/node.requestManager.spec.ts
  test/setup.ts
  test/shared.messages.spec.ts
  test/shared.queue.spec.ts
  test/utils.logger.spec.ts
  test/utils.text.spec.ts
  test/utils.time.spec.ts
  test/utils.uid.spec.ts
  yarn.lock
Labels: A-tests, D-average, T-feature

#31 Deals database class
  package.json
  src/client/dealsManager.ts
  src/node/api/index.ts
  src/node/api/router/admin.ts
  src/node/api/router/user.ts
  src/node/api/server.ts
  src/node/db/deals.ts
  src/node/db/users.ts
  src/shared/queue-old.ts
  src/shared/types.ts
  src/storage/abstract.ts
  src/storage/local.ts
  src/storage/memory.ts
  test/node.api.nodeApiServer.spec.ts
  test/node.db.deals.spec.ts
  test/node.db.users.spec.ts
  tsconfig.json
  yarn.lock
Labels: A-tests, T-feature

#32 Test/memory storage
  src/storage/abstract.ts
  src/storage/local.ts
  src/storage/memory.ts
  test/storage.memory.spec.ts
Labels: A-tests, D-easy, T-bug, T-feature
